In [1]:
# Tensorflow basic concept

# Introduction to Tensors

In [5]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
# Create tensors with tf.constant()
scalar  = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimension of a tensor
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the dimension of our vector
vector.ndim

1

In [9]:
# Create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
# Create another mt
another_mt =tf.constant([[10.,7.],
                         [3.,2.],
                         [2.,1.]], dtype = tf.float16) # Specify the datatype
another_mt

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 2.,  1.]], dtype=float16)>

In [12]:
# What's is the number dimensions of another mt
another_mt.ndim

2

In [13]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [14]:
tensor.ndim

3

What we've created so far:
* Scalar: A single number
* Vector: a number with direction
* Matrix: a 2-dimensonal array
* Tensor: a n dimensional array

Creating tensor with tf.Variable

In [15]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
# How about we try.assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# Let's try with unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random Tensors
random tensors are tensors of fixed size with random numbers

In [22]:
# Create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = tf.random.uniform(shape = (3,3))
random_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.88082564, 0.858742  , 0.5525007 ],
       [0.4542457 , 0.39547527, 0.6050514 ],
       [0.24920714, 0.3108853 , 0.18560004]], dtype=float32)>

# Shuffle the order of elements in the order

In [1]:
# Shuffle a tensor (valuable for when you want to shuffle the data, inherent order of data may not affect)

In [16]:
tf.random.set_seed(42)
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
# shuffle
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

# Other ways to make tensor

In [17]:
# Create tensors of all one
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
# Create tensors of all zeroes
tf.zeros(shape =  (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### You can also turn Numpy arrays into tensors

The main difference between NumPy and TensorFlow tensors is that tensors can be run on a GPU => faster computing

In [20]:
import numpy as np
numpy_A = np.arange(1,25, dtype = int)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
A = tf.constant(numpy_A, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

# Getting information from a tensor
* Size
* Shape
* Rank
* Axis or dimension


In [24]:
# Create a rank 4 tensors(4 dimensions)
rank_4 = tf.zeros(shape = (2,3,4,5))
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4.shape, rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensors
Tensors can be indexed just like Python lists

In [26]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension

In [28]:
rank_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
# Get the first element from each dimension from each index exvept for the final one
rank_4[:1,:1,:1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1,2],
                              [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [33]:
# Get the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [35]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[... , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [37]:
tf.expand_dims(rank_2_tensor, axis = -1) # Expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [38]:
tf.expand_dims(rank_2_tensor, axis = 0) # Expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)
** Basic operations **
* +, -, / , *

In [39]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [40]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [42]:
# We can use the tensorflow built in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix multiplication

In ml, matrix multiplication is one of the most important concept

In [43]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [45]:
X = tf.constant([[1,2,3],
                 [4,5,6]])
X.shape

TensorShape([2, 3])

In [46]:
tf.matmul(tf.transpose(X), X)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

The dot porduct
Matrix multiplication is also referred to as the dot product

- We can use:
* tf.matmul()
* tf.tensordot()

In [47]:
# Perform the dot product on X nand Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), X ,axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

In [48]:
# Perform matrix multiplication between X and Y(transposed)
tf.matmul(X, tf.transpose(X))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [50]:
tf.matmul(X, tf.reshape(X, shape = (3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [52]:
X, tf.transpose(X), tf.reshape(X, shape = (3,2))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

### Changing the datatype of the tensor

In [53]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [54]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [56]:
# Change from float32 to float16
B = tf.cast(B, dtype = tf.float16)
B.dtype

tf.float16

### Aggregating tensors

Aggregating tensors = condesing them from multiple values down to a smaller amount of values

In [57]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [58]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the mininum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [60]:
# Create a random tensor with values between 0 and 100 of size 50
E =  tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41, 30, 97, 45, 15, 72, 35, 60, 91,  5, 93, 61, 47, 53, 38, 11, 83,
       69, 94, 63, 96, 18, 11, 52, 43, 72,  0, 29,  0, 13, 85, 78, 57,  1,
       65, 43, 63, 97, 42, 67, 65, 80, 11, 99, 50, 21,  7, 51, 29,  5])>

In [61]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [62]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [63]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2453>

In [64]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [66]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [67]:
# Index on our largest value position
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [68]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [71]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [72]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [73]:
G_squeezed =tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [74]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Excersise
00. TensorFlow Fundamentals Extra-curriculum
1. Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
2. Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
* How would you calculate your grocery bill for the month and for the year using tensors?
3. Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
* Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
4. Watch the video "What's a tensor?" - a great visual introduction to many of the concepts we've covered in this notebook.

In [12]:
import tensorflow as tf
import numpy as np

In [13]:
# 2a
d = {'rice': 5, 'corriander': 2, 'ginger': 5, 'apple': 5}
bill = tf.constant(list(d.values()))
total_price = tf.reduce_sum(bill)
total_price

<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [25]:
#2b
m1 = tf.random.uniform(minval = 0, maxval = 100, shape = [30])
m2 = tf.random.uniform(minval = 0, maxval = 100, shape  = [20])
total = tf.concat([m1,m2], axis = 0)
tf.reduce_sum(total)

<tf.Tensor: shape=(), dtype=float32, numpy=2674.041>